/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "daemon_constants.h"

namespace workdaemon {

const daemonConstants g_daemon_constants;

daemonConstants::daemonConstants() {
}

} // namespace

