/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef daemon_CONSTANTS_H
#define daemon_CONSTANTS_H

#include "daemon_types.h"

namespace workdaemon {

class daemonConstants {
 public:
  daemonConstants();

};

extern const daemonConstants g_daemon_constants;

} // namespace

#endif
