/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef daemon_TYPES_H
#define daemon_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace workdaemon {

typedef int16_t Status;

typedef int64_t JobID;

typedef int64_t PartID;

typedef int64_t ChunkID;

typedef int32_t BlockID;

typedef int32_t Count;

typedef std::string URL;

typedef std::map<std::string, std::string>  Properties;

} // namespace

#endif
