/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef master_CONSTANTS_H
#define master_CONSTANTS_H

#include "master_types.h"

namespace Master {

class masterConstants {
 public:
  masterConstants();

};

extern const masterConstants g_master_constants;

} // namespace

#endif
