/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "master_constants.h"

namespace Master {

const masterConstants g_master_constants;

masterConstants::masterConstants() {
}

} // namespace

